### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by NtokozoRibane** [NtokozoRibane/Crypto_Portal#3]
[![Build Status](https://travis-ci.org/NtokozoRibane/Crypto_Portal.svg?branch=master)](https://travis-ci.org/NtokozoRibane/Crypto_Portal)

**Comment by Khendle** [comment]
We assigned the Null values to the password variable in the test script

**Comment by NtokozoRibane** [comment]
Ohh thanks will fix that
